services:
  postgres:
    restart: unless-stopped
    image: postgres:14.10-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: database
    ports:
      - '5432:5432'

volumes:
  pgdata:
