name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          envs: GITHUB_SHA=${{ github.sha }}
          script: |
            echo "=== Starting Deployment ==="

            # 1. Загружаем Node.js в PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # 2. Проверяем доступность Node.js
            echo "Node.js version: $(node -v)"
            echo "npm version: $(npm -v)"
            echo "pnpm path: $(which pnpm)"
            echo "pm2 path: $(which pm2)"

            # 3. Обновляем код
            cd /home/test-payload
            git fetch
            git reset --hard origin/main

            # 4. Устанавливаем зависимости
            /usr/local/bin/pnpm install --frozen-lockfile --prod

            # 5. Собираем проект
            /usr/local/bin/pnpm build

            # 6. Перезапускаем приложение
            sleep 5
            echo "Restarting PM2..."
            /usr/local/bin/pm2 restart 2

            # 7. Проверяем статус
            echo "PM2 status:"
            /usr/local/bin/pm2 list

            echo "=== Deployment Successful ==="
